// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIc9kTq3kJnMsIr-Pqlc9CSuSfrgfW8k0',
    appId: '1:406740018160:web:48881507c1631f6de0b335',
    messagingSenderId: '406740018160',
    projectId: 'attendance-app-6ebfb',
    authDomain: 'attendance-app-6ebfb.firebaseapp.com',
    storageBucket: 'attendance-app-6ebfb.appspot.com',
    measurementId: 'G-9VF05N3THY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEg3ASAiDlX5LTF8dU_lwwExqkeKmItoU',
    appId: '1:406740018160:android:a5923b9a7265760de0b335',
    messagingSenderId: '406740018160',
    projectId: 'attendance-app-6ebfb',
    storageBucket: 'attendance-app-6ebfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBodYeef2Vo__t9UqLx5aVAtjuh1FUjhkI',
    appId: '1:406740018160:ios:ec99a5a463a975fae0b335',
    messagingSenderId: '406740018160',
    projectId: 'attendance-app-6ebfb',
    storageBucket: 'attendance-app-6ebfb.appspot.com',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBodYeef2Vo__t9UqLx5aVAtjuh1FUjhkI',
    appId: '1:406740018160:ios:ec99a5a463a975fae0b335',
    messagingSenderId: '406740018160',
    projectId: 'attendance-app-6ebfb',
    storageBucket: 'attendance-app-6ebfb.appspot.com',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIc9kTq3kJnMsIr-Pqlc9CSuSfrgfW8k0',
    appId: '1:406740018160:web:14c6bbb5959f1402e0b335',
    messagingSenderId: '406740018160',
    projectId: 'attendance-app-6ebfb',
    authDomain: 'attendance-app-6ebfb.firebaseapp.com',
    storageBucket: 'attendance-app-6ebfb.appspot.com',
    measurementId: 'G-87432XQ9J3',
  );
}
